FROM node:22-alpine3.18 AS builder1

ADD https://github.com/NFDI4Chem/nmrium-react-wrapper.git#v0.1.0 /app

WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH

RUN npm ci
RUN npm install react-scripts@latest -g

RUN echo "export default { version: 'v0.1.0' };" > src/versionInfo.ts
COPY payload/useWhiteList.ts src/hooks/useWhiteList.ts

RUN npm run build
RUN mkdir -p /output && ( mv build/* /output || mv dist/* /output )

FROM node:22-alpine3.18 AS builder2

ADD https://github.com/NFDI4Chem/nmrium-react-wrapper.git#v0.2.0 /app

WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH

RUN npm ci
RUN npm install react-scripts@latest -g

RUN echo "export default { version: 'v0.2.0' };" > src/versionInfo.ts
COPY payload/useWhiteList.ts src/hooks/useWhiteList.ts

RUN npm run build
RUN mkdir -p /output && ( mv build/* /output || mv dist/* /output )

FROM node:22-alpine3.18 AS builder3

ADD https://github.com/NFDI4Chem/nmrium-react-wrapper.git#v0.3.0 /app

WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH

RUN npm ci
RUN npm install react-scripts@latest -g

RUN echo "export default { version: 'v0.3.0' };" > src/versionInfo.ts
COPY payload/useWhiteList.ts src/hooks/useWhiteList.ts

RUN npm run build
RUN mkdir -p /output && ( mv build/* /output || mv dist/* /output )

FROM node:22-alpine3.18 AS builder4

ADD https://github.com/NFDI4Chem/nmrium-react-wrapper.git#v0.4.0 /app

WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH

RUN npm ci
RUN npm install react-scripts@latest -g

RUN echo "export default { version: 'v0.4.0' };" > src/versionInfo.ts
COPY payload/useWhiteList.ts src/hooks/useWhiteList.ts

RUN npm run build
RUN mkdir -p /output && ( mv build/* /output || mv dist/* /output )

FROM node:22-alpine3.18 AS builder5

ADD https://github.com/NFDI4Chem/nmrium-react-wrapper.git#v0.5.0 /app

WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH

RUN npm ci
RUN npm install react-scripts@latest -g

RUN echo "export default { version: 'v0.5.0' };" > src/versionInfo.ts
COPY payload/useWhiteList.ts src/hooks/useWhiteList.ts

RUN npm run build
RUN mkdir -p /output && ( mv build/* /output || mv dist/* /output )

FROM node:22-alpine3.18 AS builder6

ADD https://github.com/NFDI4Chem/nmrium-react-wrapper.git#v0.6.0 /app

WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH

RUN npm ci
RUN npm install react-scripts@latest -g

RUN echo "export default { version: 'v0.6.0' };" > src/versionInfo.ts
COPY payload/useWhiteList.ts src/hooks/useWhiteList.ts

RUN npm run build
RUN mkdir -p /output && ( mv build/* /output || mv dist/* /output )

FROM node:22-alpine3.18 AS builder7

ADD https://github.com/NFDI4Chem/nmrium-react-wrapper.git#v0.7.0 /app

WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH

RUN npm ci
RUN npm install react-scripts@latest -g

RUN echo "export default { version: 'v0.7.0' };" > src/versionInfo.ts
COPY payload/useWhiteList.ts src/hooks/useWhiteList.ts

RUN npm run build
RUN mkdir -p /output && ( mv build/* /output || mv dist/* /output )

FROM node:22-alpine3.18 AS builder8

ADD https://github.com/NFDI4Chem/nmrium-react-wrapper.git#v0.8.0 /app

WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH

RUN npm ci
RUN npm install react-scripts@latest -g

RUN echo "export default { version: 'v0.8.0' };" > src/versionInfo.ts
COPY payload/useWhiteList.ts src/hooks/useWhiteList.ts

RUN npm run build
RUN mkdir -p /output && ( mv build/* /output || mv dist/* /output )

FROM node:22-alpine3.18 AS builder9

ADD https://github.com/NFDI4Chem/nmrium-react-wrapper.git#v0.9.0 /app

WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH

RUN export NODE_OPTIONS=--max-old-space-size=153600
RUN rm package-lock.json
RUN npm i
RUN npm i react-scripts@latest -g

RUN echo "export default { version: 'v0.9.0' };" > src/versionInfo.ts
COPY payload/useWhiteList.ts src/hooks/useWhiteList.ts

RUN npm run build
RUN mkdir -p /output && ( mv build/* /output || mv dist/* /output )

FROM node:22-alpine3.18 AS builder10

ADD https://github.com/NFDI4Chem/nmrium-react-wrapper.git#v1.0.0 /app

WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH

RUN export NODE_OPTIONS=--max-old-space-size=153600
RUN rm package-lock.json
RUN npm i
RUN npm i react-scripts@latest -g

RUN echo "export default { version: 'v1.0.0' };" > src/versionInfo.ts
COPY payload/useWhiteList.ts src/hooks/useWhiteList.ts

ENV NO_MINIFY=true
RUN npm run build
RUN mkdir -p /output && ( mv build/* /output || mv dist/* /output )

# Base image for building the application
FROM nginx:stable-alpine

# Copy the nginx configuration file
COPY payload/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder10 /output /usr/share/nginx/html/
COPY --from=builder10 /output /usr/share/nginx/html/v1.0.0
COPY --from=builder9 /output /usr/share/nginx/html/v0.9.0
COPY --from=builder8 /output /usr/share/nginx/html/v0.8.0
COPY --from=builder7 /output /usr/share/nginx/html/v0.7.0
COPY --from=builder6 /output /usr/share/nginx/html/v0.6.0
COPY --from=builder5 /output /usr/share/nginx/html/v0.5.0
COPY --from=builder4 /output /usr/share/nginx/html/v0.4.0
COPY --from=builder3 /output /usr/share/nginx/html/v0.3.0
COPY --from=builder2 /output /usr/share/nginx/html/v0.2.0
COPY --from=builder1 /output /usr/share/nginx/html/v0.1.0

# Set permissions for nginx
RUN chown -R nginx:nginx /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]