services:
  nmrium:
    image: nginx:stable-alpine
    ports:
      - 80
    environment:
      - RELEASE=${NMRIUM_RELEASE}
      - location=${NMRIUM_WRAPPER_LOCATION}
    volumes:
      - ${NMRIUM_WRAPPER_LOCATION}/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${NMRIUM_WRAPPER_LOCATION}/releases/:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]