services:
  ketchersvc:
    image: ptrxyz/chemotion:ketchersvc-2.0.1
    environment:
      - CONFIG_KETCHER_URL=http://ketchersidecar
    networks:
      - ketcher-for-sidecar
networks:
  ketcher-for-sidecar:
    external: true
