services:
  ketchersvc-211:
    image: ptrxyz/chemotion:ketchersvc-2.1.1
    environment:
      - CONFIG_KETCHER_URL=http://ketchersidecar2
    networks:
      - ketcher-for-sidecar
  ketchersvc-201:
    image: ptrxyz/chemotion:ketchersvc-2.0.1
    environment:
      - CONFIG_KETCHER_URL=http://ketchersidecar1
    networks:
      - ketcher-for-sidecar
networks:
  ketcher-for-sidecar:
    external: true
