services:
  indigo:
    image: epmlsop/indigo-service:1.34.0-rc.1
    environment:
      - PYTHONPATH=/srv/indigo-python
      - INDIGO_UWSGI_RUN_PARAMETERS=--plugin python3 --py-autoreload=1
      - PYTHONDONTWRITEBYTECODE=1
    command: supervisord -n