services:
  msconvert-312:
    image: ptrxyz/chemotion:msconvert-3.1.2
    volumes:
      - ${STORAGE}/shared/spectra/312:/shared:rw
    networks:
      - spectra-internal-312
  spectra-312:
    image: ptrxyz/chemotion:spectra-3.1.2
    volumes:
      - ${STORAGE}/shared/spectra/312:/shared:rw
    networks:
      - spectra-internal-312
  msconvert-300:
    image: ptrxyz/chemotion:msconvert-3.0.0
    volumes:
      - ${STORAGE}/shared/spectra/300:/shared:rw
    networks:
      - spectra-internal-300
  spectra-300:
    image: ptrxyz/chemotion:spectra-3.0.0
    volumes:
      - ${STORAGE}/shared/spectra/300:/shared:rw
    networks:
      - spectra-internal-300
  msconvert-220:
    image: ptrxyz/chemotion:msconvert-2.2.0
    volumes:
      - ${STORAGE}/shared/spectra/220:/shared:rw
    networks:
      - spectra-internal-220
  spectra-220:
    image: ptrxyz/chemotion:spectra-2.2.0
    volumes:
      - ${STORAGE}/shared/spectra/220:/shared:rw
    networks:
      - spectra-internal-220

networks:
  spectra-internal-312:
  spectra-internal-300:
  spectra-internal-220: