services:
  sidecar-220:
    image: ptrxyz/chemotion:ketchersvc-sc-1.10.5
    hostname: ketchersidecar220
    networks:
      - ketcher-for-sidecar
  sidecar-211:
    image: ptrxyz/chemotion:ketchersvc-sc-1.10.5
    hostname: ketchersidecar211
    networks:
      - ketcher-for-sidecar
  sidecar-201:
    image: ptrxyz/chemotion:ketchersvc-sc-1.10.5
    hostname: ketchersidecar201
    networks:
      - ketcher-for-sidecar
networks:
  ketcher-for-sidecar:
    external: true