# This works for versions 0.1.0 to 0.8.0
# Build stage
FROM node:22-alpine3.18 AS builder

# Declare build argument
ARG RELEASE
ENV RELEASE_VERSION=${RELEASE}
WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH

# Install dependencies first
COPY package.json ./
COPY package-lock.json ./
RUN export NODE_OPTIONS=--max-old-space-size=102400
RUN npm ci
RUN npm install react-scripts@latest -g

# Copy source and build
COPY . .
RUN echo "export default { version: '${RELEASE_VERSION}' };" > src/versionInfo.ts

# Create releases directory and build
RUN npm run build

RUN mkdir -p /output && mv build/* /output

FROM scratch AS copytohost
# Copy the build output to the host machine
COPY --from=builder /output /