# This works for versions 0.9.0 and above
# Build stage
FROM node:22-alpine3.18 AS builder

# Declare build argument
ARG RELEASE
ENV RELEASE_VERSION=${RELEASE}
WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH

# Install dependencies first
COPY package.json ./
RUN export NODE_OPTIONS=--max-old-space-size=153600
RUN npm i
RUN npm i react-scripts@latest -g

# Copy source and build
COPY . .
RUN echo "export default { version: '${RELEASE_VERSION}' };" > src/versionInfo.ts

# Create releases directory and build
RUN npm run build

RUN mkdir -p /output && mv dist/* /output

FROM scratch AS copytohost
# Copy the build output to the host machine
COPY --from=builder /output /